#adapters:
#  active: tui
#  configs: {}

#adapters:
#   active: generic_mqtt
#   configs:
#     broker: tcp://127.0.0.1:1883
#     topic: nms-agent/telemetry
#     qos: 1
#     retain: false
#     strict_queue_mode: true

adapters:
  active: thingsboard_mqtt
  configs:  
    broker: tcp://100.127.212.84:1883
    strict_queue_mode: true

    provisioning:
      base_url: ${TB_URL}
      device_key: ${TB_PROVISION_DEVICE_KEY}
      device_secret: ${TB_PROVISION_DEVICE_SECRET}

    thingsboard:
      api:
        base_url: ${TB_URL}
        api_key: ${TB_API_KEY}
      site:
        key: branch-b
        asset_id: a75abc20-1839-11f1-a070-473c29007b79
        asset_name: Branch-B
